spring:
    application:
        name: products
    datasource:
        url: jdbc:mariadb://localhost:3306/products
        username: root
        password: my-secret-pw
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update

aws:
    region: us-east-1
    sns:
        topic:
            products:
                events:
                    arn: product-events
    s3:
        bucket:
            invoice:
                name: pcs-invoice
    sqs:
        queue:
            invoice:
                events:
                    name: s3-invoice-events